/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence 
 * whose values do not exceed four million, 
 * 
 * find the sum of the even-valued terms.
 */

export default function sumEvenValues(max){
    console.time(`p0002: max ${max}`)
    let sum = 0;
    let i = 0, j = i + 1;

    while(j < max){
        if(j >= max) break;
        const fib = i + j;
        console.log(fib)

        if(fib % 2 !== 0) sum += fib;

        i = j;
        j = fib;
    }

    console.timeEnd(`p0002: max ${max}`)
    return sum;
}